# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

    # Clang-format for C++
    # This brings in a portable version of clang-format.
    # See also: https://github.com/ssciwr/clang-format-wheel
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.7
    hooks:
    - id: clang-format
      types_or: [c++, c]

    # CMake linting and formatting
  - repo: https://github.com/BlankSpruce/gersemi
    rev: 0.15.1
    hooks:
    - id: gersemi
      name: CMake linting
      exclude: ^.*/tests/.*/data/ # Exclude test data directories

    # Markdown linting
    # Config file: .markdownlint.yaml
    # Commented out to disable this by default. Uncomment to enable markdown linting.
  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.42.0
  #   hooks:
  #   - id: markdownlint

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell

exclude: 'cookiecutter/'
