repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell

  # Python linting and formatting
  # config file: ruff.toml (not currently present but add if needed)
  # https://docs.astral.sh/ruff/configuration/
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      - id: ruff-check
        files: ^tools/beman-tidy/
      - id: ruff-format
        files: ^tools/beman-tidy/
